#
server:
  port: 9001
spring:
  application:
    name: mall-user-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db_mall?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: Aa123456
  redis:
    host: localhost
    port: 6379
    timeout: 5s
    jedis:
      pool:
        max-active: 8
        max-wait: -1s
        min-idle: 0