server:
  name: mall-item-provider
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://111.231.193.138:3306/db_mall?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: ZhongFei-ca-2018
#
#spring:
#  datasource:
#    url: jdbc:mysql://111.231.193.138:3306/db_mall?useUnicode=true&characterEncoding=utf8&useSSL=false
#    username: root
#    password: ZhongFei-ca-2018
#    driver-class-name: com.mysql.jdbc.Driver
#
#    hikari:
#      connection-test-query: SELECT 1 FROM DUAL
#      minimum-idle: 1
#      maximum-pool-size: 5
#      pool-name: bosPoolName
#      max-lifetime: 1800000
debug: true