server:
  port: 80

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://111.231.193.138:3306/db_mall?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: ZhongFei-ca-2018
  jpa:
    show-sql: true
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: mall-item-provider
#debug: true
#spring:
#  datasource:
#    url: jdbc:mysql://192.168.1.6:3306/db_mall?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
#    username: root
#    password: Aa123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#    hikari:
#      connection-test-query: SELECT 1 FROM DUAL
#      minimum-idle: 1
#      maximum-pool-size: 5
#      pool-name: bosPoolName
#      max-lifetime: 1800000