server:
  port: 9002
spring:
  application:
    name: mall-cart-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
      host: localhost
      port: 6379
      timeout: 5s
      jedis:
        pool:
          max-active: 8
          max-wait: -1s
          min-idle: 0